application: mhack
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /pic
  static_dir: pictures

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest